name: Deploy to Heroku
on:
  push:
    branches:
      - main  # Change if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ HRKU-01c5f9f9-91ef-48ec-819e-8aaa15c96a8f }}
        run: |
          heroku container:login
          heroku container:push web --app your-heroku-app-name
          heroku container:release web --app your-heroku-app-name
